ecole01/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from intranet import views as intranet_views
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url
from django.views.static import serve



urlpatterns = [
    path('admin/', admin.site.urls),
    #url(r"^payments/", include("pinax.stripe.urls")),
    path('intranet/', include('intranet.urls', namespace='intranet')),
    path('',  RedirectView.as_view(url='/intranet/connexion')),
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

intranet/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib.auth.views import (
    password_reset, password_reset_done, password_reset_confirm,
    password_reset_complete )
from . import views

app_name = 'intranet'

urlpatterns = [
    path('', views.accueil, name='base'),
    path('accueil', views.accueil, name='accueil'),
    path('creation_inscription', views.creation_inscription, name='creation_inscription'),
    path('creation_adhesion', views.creation_adhesion, name='creation_adhesion'),
    path('creation_condition', views.creation_condition, name='creation_condition'),
    path('creation_eleves', views.creation_eleves, name='creation_eleves'),
    path('gestion_mail', views.gestion_mail, name='gestion_mail'),
    path('cours_prof', views.cours_prof, name='cours_prof'),
    path('cours_eleve', views.cours_eleve, name='cours_eleve'),
    path('validation_prof/<int:id>/', views.validation_prof, name='validation_prof'),
    path('suppression_prof/<int:id>/', views.suppression_prof, name='suppression_prof'),
    url(r'^validation_eleve/(?P<id>\d+)/(?P<result>\w+)/$', views.validation_eleve, name='validation_eleve'),
    path('documents', views.documents, name='documents'),
    path('gen_pdf/<int:fac_id>/', views.gen_pdf, name='gen_pdf'),
    path('gen_attest_pdf/<int:fac_id>/', views.gen_attest_pdf, name='gen_attest_pdf'),
    path('checkout', views.checkout, name='checkout'),
    # path('out', views.out, name='out'),
    path('checkout_inscription', views.checkout_inscription, name='checkout_inscription'),
    path('checkout_exam', views.checkout_exam, name='checkout_exam'),
    path('notifications', views.notifications, name='notifications'),
    path('statistiques', views.statistiques, name='statistiques'),
    path('statistiques2', views.statistiques2, name='statistiques2'),
    url(r'^graphs/membres.png$', views.graphs_membres,  name='graphs_membres'),
    url(r'^graphs/nbr_cours.png$', views.graphs_nb_cours,  name='graphs_nb_cours'),
    url(r'^graphs/evol.png$', views.graphs_evol,  name='graphs_evol'),
    url(r'^graphs/stats.png$', views.graphs_stats,  name='graphs_stats'),
    path('gestion_membres', views.gestion_membres, name='gestion_membres'),
    path('gestion_invitations', views.gestion_invitations, name='gestion_invitations'),
    path('gestion_relations', views.gestion_relations, name='gestion_relations'),
    path('gestion_prix', views.gestion_prix, name='gestion_prix'),
    path('gestion_articles', views.gestion_articles, name='gestion_articles'),
    path('gestion_condition', views.gestion_condition, name='gestion_condition'),
    path('gestion_factures', views.gestion_factures, name='gestion_factures'),
    path('gestion_examens', views.gestion_examens, name='gestion_examens'),
    path('remove_examens/<int:id>/', views.remove_examens, name='remove_examens'),
    path('examens_eleve', views.examens_eleve, name='examens_eleve'),
    url(r'^invitation$', views.invitation, name='invitation'),
    url(r'^article', views.article, name='article'),
    url(r'^relation/$', views.relation, name='relation'),
    url(r'^prix/$', views.prix, name='prix'),
    url(r'^mail/$', views.mail, name='mail'),
    path('mon_compte', views.mon_compte, name='mon_compte'),
    path('stripe_connect', views.stripe_connect, name='stripe_connect'),
    path('edit_compte', views.edit_compte, name='edit_compte'),
    path('edit_eleve/<int:id>/', views.edit_eleve, name='edit_eleve'),
    path('edit_eleve_adh/<int:id>/', views.edit_eleve_adh, name='edit_eleve_adh'),
    path('edit_eleve_cr/<int:id>/', views.edit_eleve_cr, name='edit_eleve_cr'),
    path('remove_eleve/<int:id>/', views.remove_eleve, name='remove_eleve'),
    path('remove_eleve_adh/<int:id>/', views.remove_eleve_adh, name='remove_eleve_adh'),
    path('remove_eleve_cr/<int:id>/', views.remove_eleve_cr, name='remove_eleve_cr'),
    path('add_eleve', views.add_eleve, name='add_eleve'),
    path('edit_pass', views.edit_pass, name='edit_pass'),
    url(r'^creation/(?P<uuid>[0-9a-f-]+)/$', views.creation, name='creation'),
    path('connexion', views.connexion, name='connexion'),
    path('deconnexion', views.deconnexion, name='deconnexion'),
    url(r'^reset-password/$', password_reset,
        {'template_name': 'intranet/reset_password.html', 'post_reset_redirect': 'intranet:password_reset_done',
         'email_template_name': 'intranet/reset_password_email.html'}, name='reset_password'),

    url(r'^reset-password/done/$', password_reset_done, {'template_name': 'intranet/reset_password_done.html'},
        name='password_reset_done'),

    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm,
        {'template_name': 'intranet/reset_password_confirm.html',
         'post_reset_redirect': 'intranet:password_reset_complete'}, name='password_reset_confirm'),

    url(r'^reset-password/complete/$', password_reset_complete,
        {'template_name': 'intranet/reset_password_complete.html'}, name='password_reset_complete')

]

intranet/views.py
from django.http import *
from django.contrib.auth import authenticate, login, logout
from django.views.generic import TemplateView
from django.shortcuts import render, redirect, get_object_or_404
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.files.storage import default_storage
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.urls import reverse
from datetime import datetime,timedelta,date

import uuid
from django.contrib.sites.shortcuts import get_current_site

from django.core.mail import send_mail
from django.template.loader import render_to_string

from django.contrib.auth.models import User
from intranet.models import Article,UserProfile,Invitation,Relation,Cour,Notification,Prix,Facture,Eleve,\
    Lesson,Attestation,Condition,Adhesion,Stats,InscriptionExamen,Examen

from django.db.models import Q, Sum
from django.utils import timezone
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.staticfiles.templatetags.staticfiles import static
from django.contrib.staticfiles.finders import find
from io import BytesIO
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
from .filters import FactureFilter
import stripe
import requests
import numpy as np

from pinax.stripe.actions import customers

import tempfile
import re
import os
import json
os.environ['MPLCONFIGDIR'] = tempfile.mkdtemp()
# do this before importing pylab or pyplot
import matplotlib
matplotlib.use('Agg')
import matplotlib.figure as mtf
import matplotlib.pyplot as plt
from matplotlib.backends.backend_agg import FigureCanvasAgg


from intranet.forms import LoginForm, RegistrationForm, RelationForm, InvitationForm, EditProfileForm, EditUserForm,\
    CoursFrom, PrixForm, FactureIdForm, ArticleForm, EditStaffProfileForm, ConditionForm, MailForm, ToMailFormset,\
    EleveFormset, PriceForm, LessonFrom, CondiForm, FactureForm, EditEleveForm, AddEleveForm,EditEleveFormset,\
    InscriptionExamenForm, ExamenForm

JOURS = ["lundi", "mardi", "mercredi", "jeudi", "vendredi", "samedi", "dimanche"]
MOIS = ["janvier", u"février", "mars", "avril", "mai", "juin", "juillet", u"août", "septembre", "octobre","novembre","décembre"]

def from_date_to_m_y(date):
    d = date.split('-')
    f = '%s_%s' % (d[1],d[0])
    return re.sub(r'^0', '', f)

def nb_new_notifs(user):
    # print(user.last_login.date())
    if user.is_superuser:
        nots = Notification.objects.filter(date__gte=user.userprofile.nots_view).count()
    else:
        nots = Notification.objects.filter(to_user=user, date__gte=user.userprofile.nots_view).count()
    # print(nots)
    return nots

def conv_date(date):
    return datetime.strptime(date, '%Y-%m-%d').strftime('%d/%m/%Y')

def conv_mois(value):
    try:
        m =value.split('_')
        return '%s %s' % (MOIS[int(m[0])-1], m[1])
    except ValueError:
        return None

def last_3_mois():
    mn = datetime.now().month
    my = datetime.now().year
    myl = my - 1
    if mn > 3:
        t3 = "%s_%s" % (int(mn)-2, my)
        t2 = "%s_%s" % (int(mn)-1, my)
        t1 = "%s_%s" % (mn,my)
        return (t3,t2,t1)
    if mn ==2:
        t3 = "%s_%s" % (12, my-1)
        t2 = "%s_%s" % (int(mn) - 1, my)
        t1 = "%s_%s" % (mn, my)
        return (t3, t2, t1)
    if mn ==1:
        t3 = "%s_%s" % (11, my-1)
        t2 = "%s_%s" % (12, my-1)
        t1 = "%s_%s" % (mn, my)
        return (t3, t2, t1)

def get_static(path):
        return find(path)

def add_tva(value,arg):
    try:
        return round(float(value) + float(value)*float(arg)/100,2)
    except (ValueError, ZeroDivisionError):
        return None

# Frais de Gestion PDF
@user_passes_test(lambda u: u.userprofile.is_adherent)
def gen_pdf(request,fac_id):
    import unicodedata
    # Create the HttpResponse object with the appropriate PDF headers.
    facture = get_object_or_404(Facture,pk=fac_id)
    admin = User.objects.get(is_superuser=True)
    if not request.user.is_superuser:
        if facture.to_user != request.user and facture.from_user != request.user:
            messages.warning(request,"Impossible d'accéder à la facture !")
            return redirect('intranet:documents')


    response = HttpResponse(content_type='application/pdf')
    # response['Content-Disposition'] = 'attachment;filename=facture_%s.pdf' % facture.pk
    fname = facture.facture_name
    chaine = unicodedata.normalize('NFKD', fname).encode('ASCII', 'ignore')
    response['Content-Disposition'] = 'filename=A_%s.pdf' % chaine.decode('UTF-8')
    buffer = BytesIO()

    p = canvas.Canvas(buffer)
    #prefix = 'https://' if request.is_secure() else 'http://'
    #image_url = prefix + request.get_host() + get_static('intranet/img/efp_logo.png')
    image_url = get_static('intranet/img/efp_logo.png')
    logo = ImageReader(image_url)
    #logo = ImageReader("https://scontent-cdt1-1.xx.fbcdn.net/v/t1.0-9/10435640_175219366143139_807238508633238110_n.png?_nc_cat=0&oh=f71fd724af3b36a77c5e2369a880beff&oe=5BEF1DBB")

    p.drawImage(logo, 50, 600, width=198,height=202, mask='auto')
    p.setLineWidth(.3)
    H, L = 830, 587
    p.setFont('Helvetica-Bold', 16)
    p.drawString(350, 720, "Facture N°A%s" % facture.nb_facture)
    p.setFont('Helvetica', 12)
    p.drawString(350, 705, "Date de facturation: %s" % facture.created.strftime("%d/%m/%Y"))
    p.drawString(350, 690, "Date d'échéance: %s" % facture.last.strftime("%d/%m/%Y"))

    if facture.from_user.is_superuser:
        p.setFont('Helvetica-Bold', 12)
        p.drawString(50, 580, "École Française de Piano")
        p.setFont('Helvetica', 12)
        # p.drawString(50, 565, "Emmanuel BIRNBAUM")
        p.drawString(50, 565, "%s"  % facture.from_user_address)
        p.drawString(50, 550, "%s %s" % (facture.from_user_zipcode, facture.from_user_city))
        p.drawString(50, 535, "01 85 09 93 87")
        p.drawString(50, 520, "info@ecolefrancaisedepiano.fr")
        p.drawString(50, 505, "https://www.ecolefrancaisedepiano.fr")

    else:
        p.setFont('Helvetica-Bold', 12)
        if facture.from_user.is_superuser:
            p.drawString(50, 580, "École Française de Piano")
        else:
            p.drawString(50, 580, "%s %s" % (facture.from_user_lastname, facture.from_user_firstname))
        p.setFont('Helvetica', 12)
        p.drawString(50, 565, "%s"  % facture.from_user_address)
        p.drawString(50, 550, "%s %s" % (facture.from_user_zipcode, facture.from_user_city))
        p.drawString(50, 535, "France")

    # Destinataire
    p.setFont('Helvetica-Bold', 12)
    p.drawString(350, 580, "%s %s" % (facture.to_user_lastname, facture.to_user_firstname))
    p.setFont('Helvetica', 12)
    p.drawString(350, 565, "%s" % facture.to_user_address)
    p.drawString(350, 550, "%s %s" % (facture.to_user_zipcode, facture.to_user_city))
    p.drawString(350, 535, "France")

    # if facture.type in ['Adhésion Elève', 'Adhésion Elèves', 'Adhésion Professeur','Adhésion élève', 'Adhésion élèves', 'Adhésion professeur']:
    #     p.drawString(50, 400, "%s %s-%s" % (facture.type,facture.created.year,facture.created.year+1))
    # else:
    #     p.drawString(50, 400, "%s" % facture.type)
    p.drawString(50, 400, "%s" % facture.type)
    p.setFont('Helvetica-Bold', 12)
    p.setStrokeColorRGB(0.7, 0.7, 0.7)
    p.setFillColorRGB(0.7, 0.7, 0.7)
    p.rect(50, 355, 501, 20, fill=1)
    p.setFillColorRGB(0, 0, 0)
    p.drawString(55, 360, "Description")
    p.drawString(250, 360, "Date")
    p.drawString(300, 360, "Qté")
    p.drawString(350, 360, "Prix unitaire")
    p.drawString(450, 360, "TVA")
    p.drawString(500, 360, "Montant")
    p.setFont('Helvetica', 12)
    p.drawString(55, 340, "%s" % facture.object)
    p.drawString(220, 340, "%s" % facture.created.strftime("%d/%m/%Y"))
    if facture.type not in ['Adhésion Elève', 'Adhésion Elèves', 'Adhésion Professeur','Adhésion élève', 'Adhésion élèves', 'Adhésion professeur'] and \
       str(facture.created) > "2018-12-03" :
        p.drawString(300, 340, "%s" % facture.h_qt)
    else:
        p.drawString(300, 340, "%s" % facture.object_qt)
    if facture.type not in ['Adhésion Elève', 'Adhésion Elèves', 'Adhésion Professeur','Adhésion élève', 'Adhésion élèves', 'Adhésion professeur']:
        p.drawString(350, 340, "%s€" % str(round(facture.price_ht / facture.h_qt,2)))
    else:
        p.drawString(350, 340, "%s€" % str(facture.price_ht/facture.object_qt))
    p.drawString(450, 340, "{0}%".format(facture.tva))
    p.drawString(510, 340, "%s€" % facture.price_ttc)
    p.line(50,330,551,330)
    p.setFont('Helvetica-Bold', 10)
    p.drawString(440, 315, "Total (HT)")
    p.drawString(440, 300, "TVA {0}%".format(facture.tva))
    p.drawString(510, 315, "%s €" % round(facture.price_ht,2))
    p.drawString(510, 300, "%s €" % round(facture.price_ttc-facture.price_ht,2))
    p.line(440, 290, 551, 290)
    p.setFont('Helvetica-Bold', 12)
    p.drawString(440, 270, "Total (TTC)")
    p.drawString(510, 270, "%s €" % facture.price_ttc)

    p.setFont('Helvetica-Bold', 11)
    p.drawString(50, 220, "Échéance:")
    p.setFont('Helvetica', 11)
    p.drawString(200, 220, "%s" % facture.last.strftime("%d/%m/%Y"))

    if facture.from_user.is_superuser:
        p.setFont('Helvetica-Bold', 10)
        p.drawCentredString(300,60,'École Française de Piano - SASU EFP')
        p.setFont('Helvetica-Oblique', 8)
        # p.drawCentredString(300,45,'4 Rue du Champ de l\'Alouette 75013 Paris')

intranet/templates/intranet/cours_eleve.html
{% extends 'intranet/base.html' %}
{% block title %}Home{% endblock %}
{% block nav_bar %}
{% include 'intranet/nav_bar.html' with nots=nots %}
{% endblock nav_bar %}

{% load intranet_extras %}
{% block content %}
 <div class="container container_extras">
            <h3 class="text-center mt-2">Liste des cours reçus</h3>
            {% include 'intranet/messages.html' with messages=messages %}
            {% if lessons_list %}
                <div class="table-responsive p-2 pb-5">
                    <!--table-bordered-->
                    <table class="table table-hover">
                        <thead>
                            <tr>
                            <th>Professeur</th>
                            <th>Date</th>
                            <th>Durée</th>
                            <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for l in lessons_list %}
                         <tr>
                            <td>{{ l.relation.teacher }}</td>
                            <td>{{ l.date}}</td>
                            <td>{{ l.nb_h }}h{{l.nb_m}}</td>
                            {% if l.is_valid_s %}
                             <td>
                                 <a class="li-ic btn" style="color: black;cursor: default;">
                                    <i class="fa fa-check fa-lg white-text" style="color: black;cursor: default;"></i>
                                 </a>
                             </td>
                            {% elif l.is_valid_s == False and l.is_unvalid == False %}
                            <td>
                                <a class="li-ic btn" href="{% url 'intranet:validation_eleve' id=l.pk result='valid' %}">
                                    <i class="fa fa-check fa-lg white-text" style="color: green;"></i>
                                </a>
                                <a class="li-ic btn" href="{% url 'intranet:validation_eleve' id=l.pk result='refus' %}">
                                    <i class="fa fa-times fa-lg white-text" style="color: red;"></i>
                                </a>
                            </td>
                            {% else %}
                             <td>
                                 <a class="li-ic btn" style="color: black;cursor: default;">
                                    <i class="fa fa-times fa-lg white-text" style="color: black;cursor: default;"></i>
                                 </a>
                             </td>
                            {% endif %}
                         </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% else %}
                <h5>Vous n'avez encore reçu aucun cours</h5>
            {% endif %}
 </div>
{% endblock content %}


{% block footer %}
{% include 'intranet/footer.html' %}
{% endblock footer %}

intranet/templates/intranet/creation_condition.html
{% extends 'intranet/base.html' %}
{% block title %}Home{% endblock %}
{% block nav_bar %}
{% include 'intranet/nav_bar.html' %}
{% endblock nav_bar %}

{% block content %}
 <div class="container container_extras" >
     <h3 class="text-center mt-2">Bienvenue sur l'intranet</h3>
     {% include 'intranet/messages.html' with messages=messages %}

     <h6><b>CONDITIONS GÉNÉRALES D'UTILISATION</b></h6>
     <p>Vous trouverez ci-dessous les conditions générales d'utilisation, merci d'en prendre note :</p>
     <p><a target="_blank" href="{{ condition.file.url }}" >conditions générales de l'efp</a></p>
     <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Validez</button>
    </form>
 </div>
{% endblock content %}


{% block footer %}
{% include 'intranet/footer.html' %}
{% endblock footer %}

intranet/templates/intranet/gestion_factures.html
{% extends 'intranet/base.html' %}
{% block title %}Mes Membres{% endblock %}

{% block nav_bar %}
{% include 'intranet/nav_bar.html' with nots=nots %}
{% endblock nav_bar %}

{% block content %}
<div class="container container_extras">
    <div class="tab-content">
        <h3 class="text-center mt-2">Créez une facture</h3>
        <p>Créez une facture en remplissant le formulaire ci-dessous</p>
        {% include 'intranet/messages.html' with messages=messages %}
        <form class="form-signin" method="POST"  role="form" action="{% url 'intranet:gestion_factures' %}">
            {% csrf_token %}
            {% include 'intranet/bs4_form.html' with form=form %}
            <div class="row spacer">
                <div class="col-4 offset-2 mt-2">
                    <button type="submit" class="btn btn-block btn-primary">Envoyez</button>
                </div>
            </div>
            </form>
    </div>
</div>
{% endblock content %}

{% block footer %}
{% include 'intranet/footer.html' %}
{% endblock footer %}>

intranet/templates/intranet/nav_bar.html
{% load static %}
{% load staticfiles %}
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">
    <img id="profile-img" style="width:50px; height:50px; border-radius: 50%;" class="img-responsive mr-3 ml-3" src="{% static 'intranet/img/efp_logo.png' %}" />
    <a class="navbar-brand" style="font-size:25px">&Eacute;cole Française de Piano</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <!---->
    <!---->
    {% if user.is_authenticated %}
        {% if user.is_superuser %}
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav ml-auto">
                    <a class="nav-item nav-link" href="{% url 'intranet:accueil' %}">Accueil</a>
                    <div class="dropdown">
                          <a class="nav-item nav-link dropdown-toggle" data-toggle="dropdown">
                            Modifications
                          </a>
                          <div class="dropdown-menu">
                                <a class="dropdown-item" href="{% url 'intranet:mon_compte' %}">Mon compte</a>
                                <a class="dropdown-item" href="{% url 'intranet:cours_prof' %}">Mes cours</a>
                                <a class="dropdown-item" href="{% url 'intranet:gestion_mail' %}">Envoyez un email</a>
                                <a class="dropdown-item" href="{% url 'intranet:gestion_factures' %}">Créez une facture</a>
                                <a class="dropdown-item" href="{% url 'intranet:gestion_condition' %}">Modifiez les conditions générales</a>
                          </div>
                    </div>
                    <div class="dropdown">
                          <a class="nav-item nav-link dropdown-toggle" data-toggle="dropdown">
                            Gestion
                          </a>
                          <div class="dropdown-menu">
                                <a class="dropdown-item" href="/admin">Administration</a>
                                <a class="dropdown-item" href="{% url 'intranet:gestion_articles' %}">Mes articles</a>
                                <!--<a class="dropdown-item" href="{% url 'intranet:gestion_membres' %}">Mes Membres</a>-->
                                <a class="dropdown-item" href="{% url 'intranet:gestion_invitations' %}">Mes invitations</a>
                                <a class="dropdown-item" href="{% url 'intranet:gestion_relations' %}">Mes relations</a>
                                <a class="dropdown-item" href="{% url 'intranet:gestion_prix' %}">Mes prix</a>
                                <a class="dropdown-item" href="{% url 'intranet:gestion_examens' %}">Mes examens</a>
                          </div>
                    </div>
                    <a class="nav-item nav-link" href="{% url 'intranet:documents' %}">Mes documents</a>
                    <a class="nav-item nav-link badge1" data-badge="{{nots}}" href="{% url 'intranet:notifications' %}">Notifications</a>
                    <div class="dropdown">
                          <a class="nav-item nav-link dropdown-toggle" data-toggle="dropdown">
                            Statistiques
                          </a>
                          <div class="dropdown-menu">
                               <a class="nav-item nav-link" href="{% url 'intranet:statistiques' %}">Statistiques</a>
                               <a class="nav-item nav-link" href="{% url 'intranet:statistiques2' %}">Graphiques</a>
                          </div>
                    </div>
                    <a class="fa fa-sign-out nav-item nav-link fa-lg mt-1" href="{% url 'intranet:deconnexion' %}" aria-hidden="true"></a>
                </div>
            </div>
        {% elif user.is_staff %}
            {% if user.userprofile.is_adherent %}
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav ml-auto">
                    <a class="nav-item nav-link" href="{% url 'intranet:accueil' %}">Accueil</span></a>
                    <a class="nav-item nav-link" href="{% url 'intranet:mon_compte' %}">Mon compte</a>
                    <a class="nav-item nav-link" href="{% url 'intranet:cours_prof' %}">Mes cours</a>
                    <a class="nav-item nav-link" href="{% url 'intranet:documents' %}">Mes documents</a>
                    <a class="nav-item nav-link badge1" data-badge="{{nots}}" href="{% url 'intranet:notifications' %}">Notifications</a>
                    <a class="fa fa-sign-out nav-item nav-link fa-lg mt-1" href="{% url 'intranet:deconnexion' %}" aria-hidden="true"></a>
                </div>
            </div>
            {% else %}
                <a class="navbar-text ml-auto">Vous n'êtes pas adhérent</a>
            {% endif %}
        {% else %}
            {% if user.userprofile.is_adherent %}
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav ml-auto">
                    <a class="nav-item nav-link" href="{% url 'intranet:accueil' %}">Accueil</span></a>
                    <a class="nav-item nav-link" href="{% url 'intranet:mon_compte' %}">Mon compte</a>
                    <a class="nav-item nav-link" href="{% url 'intranet:cours_eleve' %}">Mes cours</a>
                    <a class="nav-item nav-link" href="{% url 'intranet:examens_eleve' %}">Mes examens</a>
                    <a class="nav-item nav-link" href="{% url 'intranet:documents' %}">Mes documents</a>
                    <a class="nav-item nav-link badge1" data-badge="{{nots}}" href="{% url 'intranet:notifications' %}">Notifications</a>
                    <a class="fa fa-sign-out nav-item nav-link fa-lg mt-1" href="{% url 'intranet:deconnexion' %}" aria-hidden="true"></a>
                </div>
            </div>
            {% else %}
                <a class="navbar-text ml-auto">Vous n'êtes pas adhérent</a>
            {% endif %}
        {% endif %}
    {% else %}
        <a class="navbar-text ml-auto">Vous n'êtes pas connecté</a>
    {% endif %}

</nav>

intranet/templates/intranet/reset_password_complete.html
{% extends 'intranet/base.html' %}

{% block title %}Reset Password{% endblock %}

{% block nav_bar %}
{% include 'intranet/nav_bar.html' with nots=nots %}
{% endblock nav_bar %}

{% block content %}
<div class="container container_extras">
    <h3>Le mot de passe a bien été modifié !</h3>
    <a href="{% url 'intranet:connexion' %}">Connectez-vous !</a>
</div>
{% endblock content %}

{% block footer %}
{% include 'intranet/footer.html' %}
{% endblock footer %}

intranet/templates/intranet/statistiques2.html
{% extends 'intranet/base.html' %}
{% block title %}Home{% endblock %}
{% block nav_bar %}
{% include 'intranet/nav_bar.html' with nots=nots %}
{% endblock nav_bar %}

{% block content %}
<div class="container container_extras">
     <h3 class="text-center mt-2"> Mes statistiques 2 </h3>
     <h5> Différentes données statistiques: </h5>
    <div>
        <img src="{% url 'intranet:graphs_evol' %}" class="img-responsive rounded">
        <img src="{% url 'intranet:graphs_nb_cours' %}" class="img-responsive rounded">
    </div>
 </div>
{% endblock content %}

{% block footer %}
{% include 'intranet/footer.html' %}
{% endblock footer %}